import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'

import Landing from '../components/Landing'

let config = { api_key: process.env.NEXT_PUBLIC_API_KEY }

// DOC : https://www.brooklynmuseum.org/opencollection/api
let url = 'https://www.brooklynmuseum.org/api/v2'

const getArt = async () => {
  try {
    const response = await axios.get(`${url}/artist?limit=20&offset=0&`, {
      headers: config
    })
    console.log(response)
  } catch (error) {
    console.error(error)
  }
}

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Art app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Landing />
      </main>
    </div>
  )
}

export default Home
