import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Landing from '../components/Landing'
import LandingArts from '../components/LandingArts'
// import Exhibition from '../components/Exhibition'
// import BkmObjet from '../components/Object'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Art app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-100 ">
        <Landing />
        <LandingArts />
        {/* <Exhibition /> */}
        {/* <BkmObjet /> */}
      </main>
    </div>
  )
}

export default Home
